In [28]:
import tensorflow as tf


In [29]:
tf.__version__

'2.12.0'

In [30]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [36]:
x = tf.constant(42,name="x")

In [42]:
a = tf.constant([[1.,2.,3.],[4.,5.,6.]])

In [43]:
a.shape

TensorShape([2, 3])

In [44]:
a.dtype

tf.float32

In [45]:
tf.add(a,5)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 6.,  7.,  8.],
       [ 9., 10., 11.]], dtype=float32)>

In [47]:
a+5

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 6.,  7.,  8.],
       [ 9., 10., 11.]], dtype=float32)>

In [49]:
square_a = tf.square(a)

In [50]:
tf.sqrt(square_a)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [51]:
tf.transpose(a)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [55]:
V=tf.Variable([[3,1],[5,2]])

In [56]:
B=tf.constant([[7,8],[4,5]])

In [57]:
V+B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  9],
       [ 9,  7]], dtype=int32)>

In [66]:
VB_0=tf.concat(values= [V,B],axis=0)

In [67]:
VB_0

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 1],
       [5, 2],
       [7, 8],
       [4, 5]], dtype=int32)>

In [68]:
VB_1=tf.concat(values= [V,B],axis=1)

In [70]:
VB_1

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[3, 1, 7, 8],
       [5, 2, 4, 5]], dtype=int32)>

In [78]:
VB_1.shape

TensorShape([2, 4])

In [71]:
t_zeros=tf.zeros([3,4])
t_zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [73]:
t_ones= tf.ones([3,3])
t_ones

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [79]:
reshape_tensor = tf.reshape(tensor=VB_1,shape=[2,4])
reshape_tensor

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[3, 1, 7, 8],
       [5, 2, 4, 5]], dtype=int32)>

In [80]:
reshape_tensor = tf.reshape(tensor=VB_1,shape=[4,2])
reshape_tensor

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 1],
       [7, 8],
       [5, 2],
       [4, 5]], dtype=int32)>

In [81]:
t1 = tf.random.uniform(shape = [3,4] )
t1

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.24200082, 0.7866223 , 0.33075833, 0.7223004 ],
       [0.19463658, 0.5337827 , 0.48070908, 0.67218554],
       [0.64084315, 0.72909117, 0.80519485, 0.26630902]], dtype=float32)>

In [83]:
t3=tf.constant([[4.5,3.3],[7.5,2.2],[2.7,9.4],[6.5,8.3]])

In [85]:
t3.dtype

tf.float32

In [88]:
t3_as_int = tf.cast(t3,tf.int32)
t3_as_int

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [7, 2],
       [2, 9],
       [6, 8]], dtype=int32)>

In [91]:
t3_transpose = tf.transpose(t3_as_int)
t3_transpose

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 7, 2, 6],
       [3, 2, 9, 8]], dtype=int32)>

---





In [106]:
A = tf.constant([[5,6],[3,7]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 7]], dtype=int32)>

In [107]:
V = tf.constant([[6],[4]])

In [108]:
A_mult_V=A*V
A_mult_V

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 36],
       [12, 28]], dtype=int32)>

In [110]:
A_matmul_V= tf.matmul(A,V)
A_matmul_V

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[54],
       [46]], dtype=int32)>

In [112]:
A=tf.constant([[1,2],[3,4],[5,6],[7,8]])

In [113]:
rows,columns = A.shape

In [120]:
print("rows",(rows),"columns",columns)

rows 4 columns 2


In [127]:
A_identity_0 = tf.eye(4)
A_identity_0

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [128]:
A_identity_1 = tf.eye(4,2)
A_identity_1

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [129]:
import numpy as np


In [133]:
a = np.array([2.,5.,7.])

In [137]:
tf_a = tf.constant(a)
print(tf_a)

tf.Tensor([2. 5. 7.], shape=(3,), dtype=float64)


In [138]:
x = tf.constant([4,5,6])

In [139]:
np.array(x)

array([4, 5, 6], dtype=int32)